# FROM 
# MAINTAINER 

# COPY . .
# WORKDIR .

################### Filebeat Set #####################

# RUN curl -L -O https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-7.7.1-amd64.deb \
# && dpkg -i filebeat-7.7.1-amd64.deb \
# && rm filebeat-7.7.1-amd64.deb

# RUN rm /etc/filebeat/filebeat.yml
# COPY /beats/filebeat.yml /etc/filebeat/filebeat.yml
# RUN chmod 644 /etc/filebeat/filebeat.yml

# RUN chmod +x run.sh


######################################################

# ENTRYPOINT ["/run.sh"]
